services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\JsonRPCLogBundle\Controller\:
    resource: '../../Controller/'
  Tourze\JsonRPCLogBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\JsonRPCLogBundle\Logger\:
    resource: '../../Logger/'
  Tourze\JsonRPCLogBundle\Repository\:
    resource: '../../Repository/'
  Tourze\JsonRPCLogBundle\Service\:
    resource: '../../Service/'
  
  # 确保测试时可以访问 AdminMenu 服务
  Tourze\JsonRPCLogBundle\Service\AdminMenu:
    public: true
